services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5003:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3003:3000"
    command: npm start




