version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5003:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONPATH=/app  # This is crucial for module imports
    command: flask run --host=0.0.0.0






    









