version: "3.8"

services:
  backend:
    build:
      context: ./backend   # Points to the backend folder where the Dockerfile is located
      dockerfile: Dockerfile  # Specifies the Dockerfile in the backend folder
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5003:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0

  frontend:
    image: node:18  # Use the official node image for the frontend
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3003:3000"
    command: npm start






