name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      backend:
        image: python:3.11
        ports:
          - 5000:5000
        options: >-
          --health-cmd="curl --fail http://localhost:5000/ || exit 1"
          --health-interval=10s
          --health-timeout=30s
          --health-retries=5
      frontend:
        image: node:18
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl --fail http://localhost:3000/ || exit 1"
          --health-interval=10s
          --health-timeout=30s
          --health-retries=5

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install backend dependencies
      - name: Install backend dependencies
        run: |
          pip install -r backend/requirements.txt

      # Step 3: Run backend tests
      - name: Run backend tests
        run: |
          pytest backend --maxfail=3 --disable-warnings || true  # Placeholder

      # Step 4: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # Step 5: Run frontend tests
      - name: Run frontend tests
        working-directory: frontend
        run: npm test || true  # Placeholder

      # Step 6: Start containers interactively for debugging
      - name: Start containers interactively
        run: |
          docker-compose up --build -d
          docker ps -a
          docker exec -it backend /bin/bash || true
          docker exec -it frontend /bin/bash || true

      # Step 7: Debug containers logs (if failure occurs)
      - name: Debug containers logs
        if: failure()
        run: |
          docker ps -a
          docker logs $(docker ps -aqf "name=frontend")
          docker logs $(docker ps -aqf "name=backend")












